{
    "Board":{
        "Weight": 9,
        "Height": 9        
    },
    "Turtle":{
        "X":1,
        "Y":1
    },
    "Exit":{
        "X":9,
        "Y":6
    },
    "Mines":{
        "List": [
        {
            "X":6,
            "Y":0
        },
         {
            "X":1,
            "Y":3
        },
        {
            "X":6,
            "Y":3
        },
        {
            "X":3,
            "Y":4
        },
        {
            "X":5,
            "Y":6
        },
        {
            "X":1,
            "Y":8
        },
        {
            "X":4,
            "Y":8
        },
        {
            "X":8,
            "Y":8
        }]
    } 
}